
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_named_data_nfd_service_NfdService */

#ifndef _Included_com_example_nrtpttv2_MainActivity
#define _Included_com_example_nrtpttv2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

  /*
   * Class:     com_example_nrtpttv2_MainActivity
   * Method:    startNdnRtc
   * Signature: (Ljava/lang/Map;)V
   */
  JNIEXPORT void JNICALL
  Java_com_example_nrtpttv2_MainActivity_startNdnRtc(JNIEnv*, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
